import type { Metadata } from "next";
import "../globals.css";
import React from "react";

import { getAuthenticatedUser } from "@/features/auth/api";
import { redirect } from "next/navigation";
import Footer from "@/components/ui/Footer";
import { UserProvider } from "@/features/auth/UserContext";
import DashboardHeader from "@/components/ui/DashboardHrader";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getAuthenticatedUser();
  if (!user) {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body>
        <UserProvider user={user}>
          {" "}
          <DashboardHeader />
          {children}
        </UserProvider>
        <Footer />
      </body>
    </html>
  );
}
