import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { getAuthenticatedUser } from "@/features/auth/api";
import { redirect } from "next/navigation";
import Footer from "@/components/ui/Footer";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getAuthenticatedUser();
  if (!user) {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body>
        {children}
        {user.name}
        <Footer />
      </body>
    </html>
  );
}
